[package]
name = "cc0"
version = "0.1.0"
authors = ["Shiwei Zhang <ylxdzsw@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
ordered-float = { version = "2.1", default-features = false }

[target.'cfg(target_arch="wasm32")'.dependencies]
wee_alloc = "0.4"
