[package]
name = "cc0"
version = "0.1.0"
authors = ["Shiwei Zhang <ylxdzsw@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["lib", "cdylib"]

[profile.release]
lto = true
opt-level = 's'

[dependencies]
ordered-float = { version = "2.1", default-features = false }
